name: Test Self Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check whoami
        run: whoami

      - name: Check hostname
        run: hostname

      - name: Check directory
        run: pwd
